version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: preqindb
      POSTGRES_USER: preqinuser
      POSTGRES_PASSWORD: preqinpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
