# Generated by Django 4.2.5 on 2023-09-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RandomFloatGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_string", models.CharField(max_length=1200)),
                ("random_value", models.FloatField()),
            ],
        ),
    ]
